package com.ydj;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;

/**
 * Hello world!
 */
@SpringBootApplication
public class Application {
    public static void main(String[] args) {
        SpringApplication.run(Application.class, args);
        show1(
                0
                ,
                969.19
                ,
                14.46
        )
        ;
        show1(
                0
                ,
                222.68
                ,
                10.08
        )
        ;
        show1(
                107.4
                ,
                100.32
                ,
                0
        )
        ;
        show1(
                0
                ,
                148.19
                ,
                9
        )
        ;
        show1(
                0.4
                ,
                115.95
                ,
                0
        )
        ;
        show1(
                0
                ,
                8.72
                ,
                194.56
        )
        ;
        show1(
                0
                ,
                21.62
                ,
                21.62
        )
        ;
        show1(
                0
                ,
                82.74
                ,
                82.74
        )
        ;
        show1(
                176.28
                ,
                115.92
                ,
                0
        )
        ;
        show1(
                0
                ,
                56.77
                ,
                8.11
        )
        ;
        show1(
                0
                ,
                29.93
                ,
                106.68
        )
        ;
        show1(
                0
                ,
                30.5
                ,
                10
        )
        ;
        show1(
                1
                ,
                166.84
                ,
                0
        )
        ;
        show1(
                3.6
                ,
                96
                ,
                0
        )
        ;
        show1(
                0
                ,
                13.21
                ,
                120.48
        )
        ;
        show1(
                1
                ,
                1.26
                ,
                0
        )
        ;
        show1(
                0
                ,
                4.1
                ,
                166.08
        )
        ;
        show1(
                41.7
                ,
                28.72
                ,
                0
        )
        ;
        show1(
                0
                ,
                14.38
                ,
                37.76
        )
        ;
        show1(
                0
                ,
                123.39
                ,
                27.42
        )
        ;
        show1(
                0
                ,
                1.75
                ,
                5.29
        )
        ;
        show1(
                0
                ,
                70.4
                ,
                118.92
        )
        ;
        show1(
                0
                ,
                36.2
                ,
                85.2
        )
        ;
        show1(
                3.9
                ,
                120.96
                ,
                0
        )
        ;
        show1(
                58.5
                ,
                25.96
                ,
                0
        )
        ;
        show1(
                1
                ,
                35.3
                ,
                0
        )
        ;
        show1(
                0
                ,
                31.84
                ,
                31.84
        )
        ;
        show1(
                0
                ,
                43.2
                ,
                66.84
        )
        ;
        show1(
                31.4
                ,
                98.7
                ,
                0
        )
        ;
        show1(
                162.8
                ,
                64.88
                ,
                0
        )
        ;
        show1(
                0.6
                ,
                191.04
                ,
                0
        )
        ;
        show1(
                54.21
                ,
                102.55
                ,
                0
        )
        ;
        show1(
                0
                ,
                13.72
                ,
                64.32
        )
        ;
        show1(
                0
                ,
                57.24
                ,
                57.24
        )
        ;
        show1(
                0
                ,
                32.13
                ,
                22.95
        )
        ;
        show1(
                0
                ,
                148.92
                ,
                148.92
        )
        ;
        show1(
                0
                ,
                186.6
                ,
                198.16
        )
        ;
        show1(
                0
                ,
                115.46
                ,
                26.46
        )
        ;
        show1(
                0
                ,
                6.38
                ,
                6.38
        )
        ;
        show1(
                0
                ,
                16.56
                ,
                57.81
        )
        ;
        show1(
                0
                ,
                57.52
                ,
                172.56
        )
        ;
        show1(
                0
                ,
                52.15
                ,
                125.16
        )
        ;
        show1(
                0
                ,
                34.02
                ,
                102.06
        )
        ;
        show1(
                0
                ,
                101.08
                ,
                33.6
        )
        ;
        show1(
                0
                ,
                173.16
                ,
                27
        )
        ;
        show1(
                0
                ,
                3.74
                ,
                7.17
        )
        ;
        show1(
                0
                ,
                183.51
                ,
                4.5
        )
        ;
        show1(
                0
                ,
                18.64
                ,
                7.14
        )
        ;
        show1(
                0
                ,
                4.25
                ,
                10.69
        )
        ;
        show1(
                0
                ,
                3.72
                ,
                120.84
        )
        ;
        show1(
                0
                ,
                30.32
                ,
                60.64
        )
        ;
        show1(
                0
                ,
                27.88
                ,
                68.04
        )
        ;
        show1(
                0
                ,
                43.2
                ,
                67.92
        )
        ;
    }

    static void show1(double a, double b, double c) {

    }
}